active_stack_id: c4fcdfa8-46cf-4804-8cf3-0a8707ebefbe
active_workspace_name: default
analytics_opt_in: true
store:
  backup_directory: /mnt/c/mlopsiu_team4/services/zenml/database_backup
  backup_strategy: in-memory
  database: /mnt/c/mlopsiu_team4/services/zenml/local_stores/default_zen_store/zenml.db
  driver: sqlite
  max_overflow: 20
  pool_pre_ping: true
  pool_size: 20
  secrets_store:
    type: sql
  ssl_verify_server_cert: false
  type: sql
  url: sqlite:////mnt/c/mlopsiu_team4/services/zenml/local_stores/default_zen_store/zenml.db
user_id: 8cac3abc-0af0-45b5-a649-337610d5f446
version: 0.58.2
