defaults:
  - _self_

folds: 3

evaluation_metric: "neg_root_mean_squared_error"
cv_evaluation_metric: "mean_test_neg_mean_absolute_error"

pyfunc_predict_fn: "predict"

metrics:
  rmse: "neg_root_mean_squared_error"
  mae: "neg_mean_absolute_error"
  mse: "neg_mean_squared_error"