model_name: ResNet
artifact_path: resnet_model

tag_key: "model"
tag_value: "ResNet"

module_name: "models"
class_name: "ResNet"

params:
  module__input_size: [-1]
  module__output_size: [1]
  module__embedding_size: [16, 32, 64, 128]
  module__num_residual_blocks: [1, 3, 5, 10]
  module__dropout: [0.35, 0.5, 0.75]
  module__seed: [42]
  max_epochs: [25]
  optimizer__lr: [0.0005]
  optimizer__weight_decay: [10.0]