datasets:
  sample_size: 10000
  sample_filename: sample.csv
  version: '4.1'
  message: Added sample data for version 4.1
  remote: localstore
  target_col: deal_probability
  category_name:
  - Одежда, обувь, аксессуары
  - Детская одежда и обувь
  - Товары для детей и игрушки
  - Квартиры
  - Мебель и интерьер
  - Предложение услуг
  - Телефоны
  - Автомобили
  - Ремонт и строительство
  - Бытовая техника
  - Товары для компьютера
  city:
  - Краснодар
  - Екатеринбург
  - Новосибирск
  - Ростов-на-Дону
  - Нижний Новгород
  - Челябинск
  - Казань
  - Пермь
  - Уфа
  - Самара
  param_1:
  - Женская одежда
  - Для девочек
  - Для мальчиков
  - Продам
  - С пробегом
  - Аксессуары
  - Мужская одежда
  - Другое
  - Игрушки
  - Детские коляски
  param_2:
  - Обувь
  - Верхняя одежда
  - Платья и юбки
  - Другое
  - Трикотаж
  - Брюки
  - '1'
  - '2'
  - На длительный срок
  - Дом
  param_3:
  - Вторичка
  - 42–44 (S)
  - 44–46 (M)
  - 86-92 см (1-2 года)
  - 98-104 см (2-4 года)
  - 74-80 см (7-12 мес)
  - Без размера
  - 40–42 (XS)
  - 46–48 (L)
  - 110-116 см (4-6 лет)
