defaults:
  - kaggle
  - datasets
  - model/model
  - experiment
  - reproducibility

paths:
  root_path: /mnt/c/mlopsiu_team4

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +model: "resnet"
  run:
    dir: /mnt/c/mlopsiu_team4/outputs