#!/bin/bash

SAMPLE_OUTPUT_DIR="$1"
SAMPLE_FILENAME="$2"
# TAG NAME FOR SAMPLE
SAMPLE_DVC_MSG="$3"

echo "$SAMPLE_FILENAME"
echo "$SAMPLE_OUTPUT_DIR"

dvc add "$SAMPLE_OUTPUT_DIR/$SAMPLE_FILENAME"

git add "$SAMPLE_OUTPUT_DIR/$SAMPLE_FILENAME.dvc"

git commit -m "data samples $SAMPLE_DVC_MSG"
git push

# SET VERSION BEFORE DVC STAGING IN SAMPLE_DVC_VER_PATH content
git tag -a "$SAMPLE_DVC_MSG" -m "$SAMPLE_DVC_MSG"
git push --tags

dvc push



